name: Branch Builds
on: 
  push:
    paths-ignore:
      - '**/*.md'
      - '.all-contributorsrc'

jobs:
  build: 
    name: Build Android Mode
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checkout Examples Repository
        uses: actions/checkout@v4
        with:
          repository: processing/processing-examples
          path: processing-examples
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build with Gradle
        run: |
          echo sdk.dir=/usr/local/lib/android/sdk/ >> local.properties
          ./gradlew build

      - name: Create the mode
        run: |
          cd processing
          echo sdk.dir=/usr/local/lib/android/sdk/ >> local.properties
          ./gradlew extractAarJars dist
      # - name: Add artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: processing-${{ github.ref_name }}-${{github.sha}}-${{ matrix.os_prefix }}-${{ matrix.arch }}-ant
      #     path:  ./build/${{ matrix.os_prefix }}/processing-${{github.sha}}-${{ matrix.os_prefix}}-*
      #     retention-days: 1
